CREATE FUNCTION SPLIT_STR(
  x TEXT,
  delim VARCHAR(12),
  pos INT
)
RETURNS TEXT CHARACTER SET utf8
READS SQL DATA
DETERMINISTIC
RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(x, delim, pos),
       LENGTH(SUBSTRING_INDEX(x, delim, pos -1)) + 1),
       delim, '');