DELIMITER $$

CREATE 
	EVENT IF NOT EXISTS `EVT_CASEY_TEST` 
	ON SCHEDULE EVERY 1 MINUTE STARTS CURRENT_TIMESTAMP
			#AT CURRENT_TIMESTAMP + INTERVAL 1 MINUTE
			#| EVERY 1 MINUTE
	#ON SCHEDULE EVERY 1AssociationByDevice WEEK STARTS '2011-07-24 03:00:00' 
DO BEGIN
	Insert into CTS_DataCenter.Casey_TestEventSchedule(InsertTime)
	VALUES(Current_TimeStamp());
	
END $$